<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47" started-at="2015-03-11T16:39:46Z" finished-at="2015-03-11T16:39:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47" started-at="2015-03-11T16:39:46Z" finished-at="2015-03-11T16:39:46Z">
      <class name="rp.robotics.mapping.GridMapTest">
        <test-method status="FAIL" signature="rangeToObstacleTest()[pri:0, instance:rp.robotics.mapping.GridMapTest@f7fe8e]" name="rangeToObstacleTest" duration-ms="16" started-at="2015-03-11T16:39:46Z" finished-at="2015-03-11T16:39:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [15.0] but found [0.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [15.0] but found [0.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:241)
	at org.testng.Assert.assertEquals(Assert.java:254)
	at rp.robotics.mapping.GridMapTest.rangeToObstacleTest(GridMapTest.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rangeToObstacleTest -->
        <test-method status="PASS" signature="rectangularMapTest()[pri:0, instance:rp.robotics.mapping.GridMapTest@f7fe8e]" name="rectangularMapTest" duration-ms="16" started-at="2015-03-11T16:39:46Z" finished-at="2015-03-11T16:39:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rectangularMapTest -->
        <test-method status="PASS" signature="testMapTest()[pri:0, instance:rp.robotics.mapping.GridMapTest@f7fe8e]" name="testMapTest" duration-ms="0" started-at="2015-03-11T16:39:46Z" finished-at="2015-03-11T16:39:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMapTest -->
      </class> <!-- rp.robotics.mapping.GridMapTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
